default: &default
    class: 'VizLoFTR'
    ckpt: 'third_party/loftr/pretrained/outdoor_ds.ckpt'
    match_threshold: 0.2
megadepth:
    <<: *default
scannet:
    <<: *default
hpatch:
    <<: *default
inloc:
    <<: *default
    imsize: 1024
    match_threshold: 0.3
aachen_v1.1:
    <<: *default
    imsize: 1024
    match_threshold: 0.3
