default: &default
    class: 'VizPatch2Pix'
    ckpt: 'third_party/patch2pix/pretrained/patch2pix_pretrained.pth'
    ksize: 2
    imsize: 1024
    match_threshold: 0.25
megadepth:
    <<: *default
    imsize: 1200
scannet:
    <<: *default
    imsize: [640, 480]
hpatch:
    <<: *default
inloc:
    <<: *default
aachen_v1.1:
    <<: *default
    imsize: 1024
