default: &default
    class: 'VizTopicFM'
    ckpt: 'pretrained/model_best.ckpt'
    match_threshold: 0.2
    n_sampling_topics: 4
    show_n_topics: 4
megadepth:
    <<: *default
    n_sampling_topics: 10
    show_n_topics: 6
scannet:
    <<: *default
    match_threshold: 0.3
    n_sampling_topics: 5
    show_n_topics: 4
hpatch:
    <<: *default
inloc:
    <<: *default
    imsize: 1024
    match_threshold: 0.3
    n_sampling_topics: 8
    show_n_topics: 4
aachen_v1.1:
    <<: *default
    imsize: 1024
    match_threshold: 0.3
    n_sampling_topics: 6
    show_n_topics: 6
